# Generated by Django 6.0.5 on 2026-05-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='CollecteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('opened', 'Opened'), ('validated', 'Validated'), ('published', 'Published')], default='prepared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectes', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.filiere')),
            ],
        ),
    ]
