# Generated by Django 6.0.5 on 2026-05-22 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_studentnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentnote',
            unique_together={('collecte', 'student')},
        ),
    ]
