# Generated by Django 6.0.5 on 2026-06-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='notes.reclamationperiod'),
        ),
    ]
