# Generated by Django 6.0.5 on 2026-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_reclamation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='rattrapage',
            field=models.FloatField(default=0),
        ),
    ]
