# Generated by Django 6.0.5 on 2026-09-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_studentnote_rattrapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectenote',
            name='rattrapage_status',
            field=models.CharField(choices=[('closed', 'Closed'), ('opened', 'Opened'), ('validated', 'Validated'), ('published', 'Published')], default='closed', max_length=20),
        ),
    ]
