# Generated by Django 6.0.5 on 2026-05-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0004_alter_studentnote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='notes.filiere'),
        ),
    ]
