# Generated by Django 6.0.5 on 2026-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=2, null=True),
        ),
    ]
