# Generated by Django 6.0.5 on 2026-06-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0002_examcopy_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='ai_correction.examcopy')),
            ],
        ),
    ]
