# Generated by Django 6.0.5 on 2026-06-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0003_ocrresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai_correction.examcopy')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_correction.examquestion')),
            ],
        ),
    ]
