# Generated by Django 6.0.5 on 2026-06-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0004_extractedanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField()),
                ('teacher_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_correction', to='ai_correction.extractedanswer')),
            ],
        ),
    ]
