# Generated by Django 6.0.5 on 2026-06-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0005_aicorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='correction_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_sheets', to='ai_correction.exam')),
            ],
        ),
    ]
