# Generated by Django 6.0.5 on 2026-06-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0006_correctionsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionOCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='ai_correction.correctionsheet')),
            ],
        ),
    ]
