# Generated by Django 6.0.5 on 2026-06-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0007_correctionocrresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exam_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sheets', to='ai_correction.exam')),
            ],
        ),
    ]
