# Generated by Django 6.0.5 on 2026-06-24 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0008_examsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='ai_correction.examsheet')),
            ],
        ),
    ]
