# Generated by Django 6.0.5 on 2026-07-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0009_examocrresult'),
        ('notes', '0007_reclamation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='notes.filiere'),
            preserve_default=False,
        ),
    ]
