# Generated by Django 6.0.5 on 2026-07-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0010_exam_filiere'),
        ('notes', '0007_reclamation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='collecte',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='ai_exams', to='notes.collectenote'),
            preserve_default=False,
        ),
    ]
