# Generated by Django 6.0.5 on 2026-07-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0011_exam_collecte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='matiere',
        ),
    ]
