# Generated by Django 6.0.5 on 2026-07-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0012_remove_exam_filiere_remove_exam_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCopyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exam_copies/')),
                ('page_number', models.PositiveIntegerField()),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ai_correction.examcopy')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
