# Generated by Django 6.0.5 on 2026-07-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_correction', '0013_examcopypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionSheetPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='correction_sheets/')),
                ('page_number', models.PositiveIntegerField()),
                ('correction_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ai_correction.correctionsheet')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSheetPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exam_sheets/')),
                ('page_number', models.PositiveIntegerField()),
                ('exam_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ai_correction.examsheet')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
